spring:
  application:
    name: ecommerce
  datasource:
    url: jdbc:mysql://localhost:3306/java_ecommerce? createDatabaseIfNotExist=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ''
  jpa:
    show-sql: true
    database: mysql
    hibernate: 
      ddl-auto: create-drop
server:
  port: 8081
